# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carlos_Home', '0005_auto_20160414_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(max_length=1),
        ),
    ]
