# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Carlos_Home', '0006_auto_20160414_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('post_imagen', models.ImageField(upload_to='post_imagen/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_video', embed_video.fields.EmbedVideoField(blank=True, help_text='This is a help text', null=True, verbose_name='My video')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carlos_Home.Categoria')),
            ],
        ),
    ]
