# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carlos_Home', '0007_categoria_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_video',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
